### ISSUE TITLE
Support for Lbreelec

### ISSUE THREAD

**Issue by keiem** [NapoleonWils0n/kodi-playercorefactory#102]
Hello,

I want to use the ffmpeg scripts to record content on Libreelec.  Is there a way to use the bashscripts on libreelec?

**Comment by NapoleonWils0n** [comment]
hi mate

i think libreelec is like openelec and doesnt have a package manager like apt to install packages
and also has a read only file system so you cant install anything 

you could try using osmc or raspenbian instead of libreelec
osmc is based on debian so you can install the scripts

https://osmc.tv/

unfortunately you can install anything on libreelec so you would need to switch to osmc or raspbian

there is new version of the kodi recording scripts written in python called pilfer
which is more advanced than the bash version and will catch more urls

https://github.com/NapoleonWils0n/pilfer

development has switched to pilfer the bash scripts still work
but ill only being doing updates to pilfer

**Comment by keiem** [comment]
Thanks for the answer.  I will check out pilfer.

**Comment by NapoleonWils0n** [comment]
hi mate

pilfer can also rip audio as well

here are the youtube videos showing you how to use and install pilfer

https://www.youtube.com/watch?v=uKRU74Uqj1s&list=PL7hhhG5qUoXmtylBpTV4AdjFkYOj2soEB

**Comment by Topicform** [comment]
Hi JACK, CIAO from Italy... New version of pilfer? Pilfer is the number
one, thank you so much T3rmin8tor.

Paolo

Il mar 26 giu 2018 21:14 NapoleonWils0n <notifications@github.com> ha
scritto:

**Comment by NapoleonWils0n** [comment]
hi mate

i havent spoken to the t3rmin8tor for a while
so im not sure about any uodates

**Comment by Topicform** [comment]
Ok mate, good job and health :)

Paolo

Il mer 27 giu 2018 14:24 NapoleonWils0n <notifications@github.com> ha
scritto:
