### ISSUE TITLE
Chrome launcher on Kodi

### ISSUE THREAD

**Issue by Sparkplugs** [NapoleonWils0n/kodi-playercorefactory#107]
Hi Napoleon,

Hope you're keeping well. Thoroughly enjoying your playercorefactory program, its running like a dream.
I'm writing to enquire as to whether there's a way of running the Chrome browser or any other web browser in Kodi? I've searched the web for guidance but most of the forums are over a year old.
The reason for this is I'm trying to capture C4 programs and I've found an addon for Chrome that allows me to view the UK tv channels, as I'm currently living in Canada. I'm running Debian Stretch with Kodi v1. 
Any suggestions would be greatly appreciated.

Thank you for all your help.
Sparkplugs

**Comment by NapoleonWils0n** [comment]
Hi Sparkplugs

good to hear from you mate

funny you should mention channel 4,
because thats actually something ive been working on for myself

i actually have 2 solutions for recording uk tv channels inside kodi or on the command line
so you can record bbc 1, bbc 2, itv, channel 4 and channel 5

using a kodi addon i built or a custom python script for recording on the command line

but you would need to get a vpn because of geo blocking as it only works in the uk

i would recommend [privateinternetaccess](https://www.privateinternetaccess.com/)
which cost $25 a year and you can use on 5 devices at once,
and will allow you to get round geo blocking

also id recommend switching to pilfer which is a python version of kodi-playercorefactory script
which is much more advanced and will catch more urls from kodi

[pilfer](https://github.com/NapoleonWils0n/pilfer)

could you give me an email on this address so we can have a private chat

t43InvisibleMan@gmail.com

and ill hook you up
