### ISSUE TITLE
Recording catch up TV

### ISSUE THREAD

**Issue by Sparkplugs** [NapoleonWils0n/kodi-playercorefactory#11]
Hi Napole0n,

I can record and save the major "live" TV channels using Kodi and switching to the VLC player. But it doesn't work when I try to record "catch up" TV from the hub or iplayer. It goes through the motions and appears to be recording whilst playing in the background, but when I check later there is no file saved - anywhere. 
I'm more than likely doing something wrong somewhere. Have you any advice or a video I can check out. Hope this makes sense.

Many Thanks
Sparkplugs

**Comment by NapoleonWils0n** [comment]
Hi Sparkplugs

The BBC iPlayer site was updated and the iPlayer addon stopped working for a while, but there is a new update for the iPlayer addon which is working again
However i have noticed the hls streams which have a bit rate of 8000 dont work, but all the other streams work. Make sure you have the latest version of the iPlayer addon 

Which addon do you mean by the hub ?

What operating system do you use, windows 7, 8 or 10, mac osx or linux

**Comment by Sparkplugs** [comment]
Hi Napole0n,

Thank you for getting back to me so quickly. I will carry out these updates.
When you say hls streams, do you mean the kbps which are coloured red or green and range from 396 to 800 kbps in red and 800 to 8490 kbps in green in kodi? If not can you please tell me where this would be.

The other addon I mean is the ITV hub. Also, my OS is Linux mint - cinnamon.

Cheers
Sparkplugs

**Comment by NapoleonWils0n** [comment]
Hi Sparkplugs

on the bbc iplayer the highest quality green stream usually doesnt work, 
its usually marked Akami, all the other links work

the version of iPlayer im using is 0.2.1

you can also record from live tv from the itv player and all the catchup channels
i think they use rtmp streams so make sure you have rtmpdump installed

thank god a fellow linux user, took me over 12 hours to get mpv working on windows vs a couple of minutes on linux

do a git pull and install mpv, then copy the new playercorefactory.xml file to your kodi userdata directory

hope your enjoying linux

i have a git repository where i keep all my linux tips which you might find useful

https://github.com/NapoleonWils0n/cerberus

let me know if you have any problems

**Comment by Sparkplugs** [comment]
Hi Napole0n,

Sorry to keep pestering you with my problems and thanks for cerberus.

My iPlayer is already the latest version as you stated above - 0.2.1 and I've done what you suggested - git pull the latest playercorefactory into my userdata dir and installed mpv.
Which the good news is I've successfully managed to record from the ITV hub using the mpv, thank you. But I still cannot manage to record from the iPlayer using mpv or vlc. I can view the programme and it appears to be recording but nothing is being saved. I also followed your instructions from one of your you-tube tutorials and let the programme run until the end in case the recording was saved once the programme had ended, but still no luck...........any ideas?

I use to be a Windows worshipper but it's way to unnecessarily busy to do anything like this, thank god for Linux, Google and people like you!

Cheers
Sparkplugs

**Comment by NapoleonWils0n** [comment]
Hi Sparkplugs

Not pestering me at all mate, happy to help

You should be using ffmpeg to record instead of vlc or mpv
to install ffmpeg just run 

sudo apt-get install -y ffmpeg

Also make sure to install rtmpdump

sudo apt-get install -y rtmpdump

If you look in the git repo in linux/combined you will see a playercorefactory.xml file

https://github.com/NapoleonWils0n/kodi-playercorefactory/blob/master/linux/combined/playercorefactory.xml

stop kodi and then copy the linux/combined/playercorefactory.xml to your kodi userdata directory, then restart kodi 

When you press y on the keyboard you should see an option called record which uses ffmpeg to record videos, select record and it will save the video to the desktop

You can edit the playercorefactory.xml file and remove any options you dont want

if you scroll to the bottom of the playercorefactory.xml file you will see you can set the default player for kodi by uncommenting the various players

So when you click on a link in kodi it will automatically open the default player you have set, eg mpv or vlc

you can also set ffmpeg as the default player by uncommenting the record player.
so every link you click on will automatically record the video to the desktop using ffmpeg

let me know if you get stuck and ill point you in the right direction

**Comment by Sparkplugs** [comment]
Hi Napole0n,

Got stuck at the first hurdle I'm afraid.
Went to install ffmpeg and received the following error message:-

sparkplugs@sparkplugs-System-Product-Name ~ $ sudo apt-get install -y ffmpeg
[sudo] password for sparkplugs: 
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Package ffmpeg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ffmpeg' has no installation candidate

I then tried the following command

sparkplugs@sparkplugs-System-Product-Name ~ $ git clone git://source.ffmpeg.org/ffmpeg.git ffmpeg
Cloning into 'ffmpeg'...
remote: Counting objects: 468365, done.
remote: Compressing objects: 100% (97243/97243), done.
remote: Total 468365 (delta 374246), reused 463976 (delta 370355)
Receiving objects: 100% (468365/468365), 77.20 MiB | 9.90 MiB/s, done.
Resolving deltas: 100% (374246/374246), done.
Checking connectivity... done.
sparkplugs@sparkplugs-System-Product-Name ~ $ 

But still no joy. I'm not sure even that ffmpeg has been installed correctly?
Also, should I be making any changes to your playercorefactory.xml file in order for the video to be saved to a specific directory?

Many Thanks
Sparkplugs

**Comment by NapoleonWils0n** [comment]
HI Sparkplugs

looks like linux mint doesnt have ffmpeg in its repos so you have to add it using a ppa

i found this guide
https://mintguide.org/video/339-installing-ffmpeg-library-on-linux-mint-via-ppa.html

here are the steps

sudo add-apt-repository ppa:mc3man/trusty-media
sudo apt-get update
sudo apt-get install ffmpeg

if you want to make changes to the scripts you will need to fork the git repository otherwise when you do a git pull your changes will be overwritten

https://help.github.com/articles/fork-a-repo/

after you have forked the git repo you would then need to edit the rip-record script and change the location where the videos are saved

**Comment by Sparkplugs** [comment]
Hi Napoleon,

That worked a treat, ffmpeg installed. I also found Handbrake there which was useful.
But here's the thing.
I can record live tv on iplayer with the combined playercorefactory - record (ffmpeg) button, but I can't record "catch up" tv on the iplayer 
and
I can record "catch up" TV on ITV player with mpv capture but the mpv dump won't work.
Are both the problems associated and share the same issue and do you think the issue is something to do with my rtmpdump. Does Linux mint support rtmpdump?

Not sure if this makes sense, I seemed to be going round in circles at the mo, is there a way to remember what player goes with what channel? 

Please point me in the right direction.
Many Thanks
Sparkplugs

**Comment by NapoleonWils0n** [comment]
Hi Sparkplugs

glad you got ffmpeg working

from memory i think the catch up on iplayer and itv uses rtmp streams, so you need to install rtmpdump

i think rtmpdump is in the linux mint repos: 
https://community.linuxmint.com/software/view/rtmpdump

you can check if rtmpdump is in the linux mint repository by running this command in the terminal

apt-cache search rtmpdump

if rtmpdump is in the linux mint repo you can install it by running this in the terminal

sudo apt-get install rtmpdump

if its not in the repo you may need to find a ppa for rtmpdump

you should be able to use the record (ffmpeg) button to record 99% of streams from kodi
i would recommend using ffmpeg instead of mpv to record

i think you just need to install rtmpdump, i can record both live tv and catch from iPlayer and ITV

handbrake top tip
you can also use handbrake to batch convert lots of videos at once, by creating a queue have a look at the manual

**Comment by Sparkplugs** [comment]
Hi Napoleon,

Great stuff, can now record live and catch tv on all channels. But when I go to dump the stream without displaying it. The file appears on my desktop and saves the stream up to about 660kb and a couple of times its gone to about 14mb but then stops. I've checked the playercorefactory file against your git files, in case anything has changed but they're exactly he same. 
Sorry for all your time I'm taking up but if you know the issue with this, please let me know.

Thank you for all your previous solutions
Sparkplugs

**Comment by Sparkplugs** [comment]
Hi Napoleon,

Me again. I just been going over your earlier tutorials on Youtube and there's a code called - ffmpeg-Save. If I wrote that into my combined Playercorefactory.xml file, would that solve my problem or is it now obsolete.

Many Thanks
Sparkplugs

**Comment by NapoleonWils0n** [comment]
Hi Mate

thats old code

you should just need ffmpeg and rtmpdump installed,and copy the playercorefactory.xml to your kodi userdata folder
