### ISSUE TITLE
I wish this excellent software works on newest Linux Mint 22 Wilma

### ISSUE THREAD

**Issue by Net12-2** [NapoleonWils0n/kodi-playercorefactory#121]
Unfortunately I couldn't make it work on Mint 22 secondary Team Kodi PPA is not maintained due to the previous sole maintainer stepping away from the responsibility; so I was only able to install Kodi via Flatpak. This kodi-playercorefactory script doesn't work with Flatpak installed kodi. Is it possible to make it work, please? Thank you

**Comment by NapoleonWils0n** [comment]
Hi Mate, pilfer is the new version of these scripts using python

https://github.com/NapoleonWils0n/pilfer

https://odysee.com/@NapoleonWils0n:6/pilfer-the-new-python-script-to-record:3

so you should use pilfer instead of these scripts 
which are updated anymore

flatpak sandboxes applications so they cant access the file system or run scripts

i dont know if you can use flatseal to remove the sandbox and allow the scripts to run
im not sure what you would need to do, and im not running linux so i cant test it

unless you can figure out a way to use flatseal to allow the scripts to run on mint
then i think you are going to have lots of issue with kodi installed using flatpak and trying to run the scripts

https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux

"Debian which includes Kodi in their distribution. "

sound like kodi is still in the debian and ubuntu repositories

flatseal

https://flathub.org/apps/com.github.tchx84.Flatseal

https://github.com/tchx84/Flatseal
