### ISSUE TITLE
Not so much an issue, more assistance required...

### ISSUE THREAD

**Issue by gb160** [NapoleonWils0n/kodi-playercorefactory#15]
As stated really,hope u don't mind me contacting u on here, i looked at your twitter but that doesn't seem very active.
 i used your excellent guide to enable me to use mpv as an external player in kodi...im using OS X 10.11.5.
i wanted to use mpv for one reason...the interpolation capabilities.
You're probably aware of it but it enables you to watch 24/25 fps video smooth as butter on a 50/60hz screen....i was absolutely amazed at the quality produced via mpv with this feature enabled, and as i view all my live tv stuff from an iptv provider it really does make a hell of a difference...

Anyway, the problem is this, if i open a url in mpv from the terminal...everything works fine, and the interpolation can be triggered on and off from a keypress....perfect.
The problem is if I'm using mpv as an external player in kodi...the stream starts playing but if i try to switch interpolation on mpv crashes instantly.
Ive been pulling my hair out trying to fix it, I'm happy to give you a login to my iptv provider if u can help solve this.
I've checked kodi logs and nothing notable gets reported there...and the mpv logs are next to useless.

the guide i used to install mpv and get it working is here:
https://www.reddit.com/r/osx/comments/4ljbdq/mpv_tutorial_and_60_fps_playback_on_os_x/

obviously if you can't be bothered or are too busy then feel free to close the issue and ill carry on banging my head against the wall !!

Regards.

**Comment by NapoleonWils0n** [comment]
Hi gb160
Dont mind you contating me at all no problem
No im not active on Twiiter at all havent used it in ages

Best place to have conversations is on the Kodi forum, that way other users can help out or benefit from any tips 

I try to keep the issue's on github related to the scripts otherwise looks like there are unsolved issues, not a biggy

I have a thread on the Kodi forum here, if you register you can comment or pm me
http://forum.kodi.tv/showthread.php?tid=216111

Do you mind if we carry on the conversation on the Kodi forum as there may be other mac users using mpv who may have an answer to your mpv issue

Got a better chance of resolving the issue the more people that can get involved in the conversation

I have 2 youtube accounts, github issue and the kodi forum, so difficult to keep track of it all. 
I try and keep github for issues related to the scripts, youtube comments for quick replies and conversations on the Kodi forum otherwise my brain will explode

Heres my thoughts

Are you using any command line arguments with mpv in the terminal to play the videos ?

eg i use alsa which looks like this on the command line

mpv --ao=alsa:resample=yes:device=[plughw:0,0] video.mkv

You can add the command line options to the mpv config without the --

eg this is my mpv.conf with the same option

ao=alsa:resample=yes:device=[plughw:0,0]

Do you mind if we carry on the conversation on the Kodi forum and ill close the issue here. Im not closing the conversation just need to transfer to the kodi forum, getting a lot of help request today and need to spread the workload

Need to do some crowd sourcing mpv help

**Comment by gb160** [comment]
No worries...thanks for the prompt reply, I'll pester u on the kodi forum shortly ;)
I'm watching the f1 in remarkably smooth 50fps from a 25 fps source!
