### ISSUE TITLE
windows 10

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#17]
I Upgraded to windows 10 but i still have ubuntu, the reason why i switched back to windows is that ubuntu doesnt have a pvr  that windows has. To make it short, I watched your video for installing it on windows and i used step by step like in the video, saving url worked fine but when i used the command "bash" before a script in the terminal, it says  bash is not a recognized command. I tried the rip-record-batch and that is what it says. I am hoping windows 10 is not like windows 7 error/bug thingy.

**Comment by steve55792** [comment]
i probably figured  it out somehow windows command prompt is crap but some reason the MINGW32 Command prompt is working. what part  do i have to switch?

**Comment by NapoleonWils0n** [comment]
Hi Steve, the bash is not a recognized command error is a windows bug going back to windows 7. 

i made a video here showing how to fix the windows error

https://www.youtube.com/watch?v=Xc5QwVR1v9k

Try googling for "windows forgets system path" and you'll see how old the bug is

What happens is windows forgets whats in its windows system path and so cant find bash,
the fix is to edit the windows system path but not change the path, just click ok

or you can copy the system path into notepad ++ on a single line and save it to the desktop. Then delete you windows system path and then add it back from the text file you saved to the desktop and click ok

then windows remembers whats in its windows system path and bash will work again.
you may need to open a new terminal for it to pick up the changes. 

Unfortunately its a bug in the windows operating system and you will get that error from time to time. Thats why i recommend using Linux if possible

Not sure why MINGW32 Command prompt works but not the normal terminal, 
try editing your windows system path and maybe rebooting and see if bash works again
