### ISSUE TITLE
rip-record error

### ISSUE THREAD

**Issue by hejazb** [NapoleonWils0n/kodi-playercorefactory#2]
Hi Dear:Sir
I have followed your instruction to use Playercorefactory file to record from Stalker-iptv in windows 10 with Kodi 15.2. When pushing "Y" key the long menu pops up, lf I select Play, the ffmpeg player plays the content, but if I use the record, nothing is recorded. I get a new video.mkv file but it is empty. I tried to use command line, then I get error recording unknown time stamp. The strange thing is, if I use Aljazeera news channel then no problem because, it does not use ffmpeg for recording, following is the error I get while using command line to record from Stalker Iptv from Kodiland(NFPS) to record, no matter what channel the error is the same. I tried to record BBC America channel.

Microsoft Windows [Version 10.0.10240](c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Robert\Desktop>bash rip-record videourl.txt
Input #0, hls,applehttp, from 'http://31.220.40.117:80/LiveEdge/BBCAmericaHD/chunklist_w1273648558_b1000000.m3u8?token=b51d08e1bde4bbbc9b9d5c020f41714d  ':
  Duration: N/A, start: 72950.455000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Data: timed_id3 (ID3  / 0x20334449)
    Stream #0:1: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 720x480 [SAR 10:11 DAR 15:11], 59.94 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:2: Audio: mp2 ([4][0][0][0] / 0x0004), 48000 Hz, stereo, s16p, 128 kb/s
[matroska @ 044ad520] Codec for stream 0 does not use global headers but container format requires global headers
[matroska @ 044ad520] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, matroska, to 'C:\Users\Robert/Desktop/video.mkv':
  Metadata:
    encoder         : Lavf57.19.100
    Stream #0:0: Video: h264 (H264 / 0x34363248), yuv420p, 720x480 [SAR 10:11 DAR 15:11], q=2-31, 59.94 fps, 29.97 tbr, 1k tbn, 90k tbc
    Stream #0:1: Audio: mp2 (P[0][0][0] / 0x0050), 48000 Hz, stereo, 128 kb/s
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:2 -> #0:1 (copy)
Press [q] to stop, [?] for help
[matroska @ 044ad520] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[matroska @ 044ad520] Can't write packet with unknown timestamp
av_interleaved_write_frame(): Invalid argument
[matroska @ 044ad520] Can't write packet with unknown timestamp
Error writing trailer of C:\Users\Robert/Desktop/video.mkv: Invalid argumentframe=    5 fps=0.0 q=-1.0 Lsize=      23kB time=00:00:00.02 bitrate=7713.3kbits/s  
video:29kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

Please, let me know if you have a fix for this issue. l surely appreciate your precious work and willing to do some test for you. I am a retired senior citizen spending my time to learn new stuff.
Again thank you and wish you best.
Hejazb

**Comment by NapoleonWils0n** [comment]
Hi Hejazb

I have fixed the bug you found, do a git pull to update the scripts 

You should then be able to record all the stalker channels, either from within kodi or on the command line

Ill do a video explaining what the bug was and how i fixed it

Thanks for explaining the error clearly and posting the logs that really helped me figure out what the problem was

I tried recording BBC America from within Kodi and on the command line and it works

Please let me know if you can record the stalker channels after you do a git pull

I hope you didnt miss your favourite show 

I also have a git repository with all my code snippets and how to's you might find interesting

https://github.com/NapoleonWils0n/cerberus

NapoleonWils0n

**Comment by hejazb** [comment]
Hi Dear: Sir
Thank you so much for taking time and fixing the recording issue. Yesterday I tried it without knowing you have fixed the rip-record script (I used the old script) and val la, it was working. I thought it was server side error and I tried to let you know what happened then I saw your note. What I did not mention in my error report was, I have two systems Laptop (Win 8.2 Pro 64 bit) and tablet which is Win 10 32bit. I did not have no problem while using Laptop no matter Stalker IPTV or other repository add-ons. I just wanted to let you know that it works fine in both systems now. Again thank you for your excellent job. I suggest. that your training videos be presented in pure systems not in virtual machines, then following instructions would be much easier, of course, it is much work upon you, but since you are scarifying so much of your time to help humanity, I think it worth it. Again thank you very so much, please keep up the hard work.
I wish you best.
Hejazb

**Comment by NapoleonWils0n** [comment]
Hi Hejazb
Im glad everything is working for you now

I only have a linux laptop that's why i have to run windows in a virtual machine to test the scripts 
Thanks for your feedback really kind of you

If you have any problems raise an issue on github or leave a comment on my youtube channel

Ill mark this issue as closed

All the best
