### ISSUE TITLE
forked process 8472 died unexpectedly

### ISSUE THREAD

**Issue by sumitdipsite2005** [NapoleonWils0n/kodi-playercorefactory#3]
Well.. it doesnt work for me. I tried it once on mac.. i tried it this time on windows.. and it doesn't work.. i am doing everything exactly in the steps mentioned in the video in you tube as well on here but it doesnt work.

Right now when i click play in kodi it gives this error:

 stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
Stack trace:
Frame        Function    Args
00000000000  00180071F8E (00180212FDC, 00180212E86, 00000400000, 000005FEE10)
00000000000  00180046E22 (000005FFE78, 00000000000, 00000000000, 00000002000)
00000000000  00180046E62 (00000600000, 00000800000, 00000400000, 00000600000)
00000000000  00180047161 (00000000000, 00100401000, 000002DE000, 00000000000)
00000000000  001800471AE (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100472DD1 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00100401000)
00000000000  7FFBB9748102 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  7FFBBAF2C2E4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
      1 [main] bash 7064 fork: child -1 - forked process 6296 died unexpectedly, retry 0, exit code 0x100, errno 11
/cygdrive/c/Users/XXXXXXXX/git/kodi-playercorefactory/bash-scripts-windows/rip-play: fork: retry: No child processes
1036800 [main] bash 5400 C:\cygwin\bin\bash.exe: **\* fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
Stack trace:
Frame        Function    Args
00000000000  00180071F8E (00180212FDC, 00180212E86, 00000400000, 000005FEE10)
00000000000  00180046E22 (000005FFE78, 00000000000, 00000000000, 00000002000)
00000000000  00180046E62 (00000600000, 00000800000, 00000400000, 00000600000)
00000000000  00180047161 (00000000000, 00100401000, 00000332000, 00000000000)
00000000000  001800471AE (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100472DD1 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00100401000)
00000000000  7FFBB9748102 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  7FFBBAF2C2E4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
1071218 [main] bash 7064 fork: child -1 - forked process 5400 died unexpectedly, retry 0, exit code 0x100, errno 11
/cygdrive/c/Users/XXXXXXXXXX/git/kodi-playercorefactory/bash-scripts-windows/rip-play: fork: retry: No child processes
3137914 [main] bash 5520 C:\cygwin\bin\bash.exe: **\* fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
Stack trace:
Frame        Function    Args
00000000000  00180071F8E (00180212FDC, 00180212E86, 00000400000, 000005FEE10)
00000000000  00180046E22 (000005FFE78, 00000000000, 00000000000, 00000002000)
00000000000  00180046E62 (00000600000, 00000800000, 00000400000, 00000600000)
00000000000  00180047161 (00000000000, 00100401000, 000003DE000, 00000000000)
00000000000  001800471AE (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100472DD1 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00100401000)
00000000000  7FFBB9748102 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  7FFBBAF2C2E4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
3212324 [main] bash 7064 fork: child -1 - forked process 5520 died unexpectedly, retry 0, exit code 0x100, errno 11
/cygdrive/c/Users/XXXXXXXXXX/git/kodi-playercorefactory/bash-scripts-windows/rip-play: fork: retry: No child processes
7294761 [main] bash 8472 C:\cygwin\bin\bash.exe: **\* fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
Stack trace:
Frame        Function    Args
00000000000  00180071F8E (00180212FDC, 00180212E86, 00000400000, 000005FEE10)
00000000000  00180046E22 (000005FFE78, 00000000000, 00000000000, 00000002000)
00000000000  00180046E62 (00000600000, 00000800000, 00000400000, 00000600000)
00000000000  00180047161 (00000000000, 00100401000, 0000024D000, 00000000000)
00000000000  001800471AE (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100472DD1 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00100401000)
00000000000  7FFBB9748102 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  7FFBBAF2C2E4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
75059569 [main] bash 7064 fork: child -1 - forked process 8472 died unexpectedly, retry 0, exit code 0x100, errno 11
/cygdrive/c/Users/XXXXXXXXXX/git/kodi-playercorefactory/bash-scripts-windows/rip-play: fork: retry: No child processes

Do you have any ideas why?

P.S. - i havent executed the below steps -
windows notify-send
unzip the notify-send.zip
add notify-send to windows system path
windows install aria2c

because i feel they are optional to the working. Are they?

**Comment by sumitdipsite2005** [comment]
OK. System restart solved the above issue but it still does not work on clicking play in Kodi. When i click play in Kodi, the stream stops in kodi with a message to click ok when the playback has ended. The terminal tries to do something but then nothing happens.

**Comment by NapoleonWils0n** [comment]
HI Mate

Sorry your having a bit of grief getting set up
Have you tried playing several different urls from different addons
Or are you having problems with a particular addon if so which one

notify-send will give you desktop notifications when recordings have finished
aria2c is used in a bash script to make batch download videos with youtube-dl faster
You dont need to install either notify-send or aria2c to play, record or stream videos

So when you press y on the keyboard while and video is playing and select play, 
the terminal opens but doesnt play the video.
And you get a message saying click ok when playback has ended in kodi

Things to check 

1- ffmpeg
https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/windows#ffmpeg

You have installed ffmpeg, ffplay, and ffprobe to C:\ffmpeg\bin
C:\ffmpeg\bin\ffmpeg
C:\ffmpeg\bin\ffplay
C:\ffmpeg\bin\ffprobe

2 - cygwin
https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/windows#cygwin

install cygwin
install sed and grep with cygwin if they arent installed
add cygwin to your windows system path

3 - git
https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/windows#git-install

install git
select 2nd option for path not git bash shell
Use Git from the Windows Command Prompt
Checkout as--is, commit Unix-style line endings

4 - clone the kodi-playercorefactory git repository

create a folder called git in your home folder
open a terminal, and change directory into the git folder

cd git
git clone https://github.com/NapoleonWils0n/kodi-playercorefactory.git

5 - playercorefactory.xml

copy the playercorefactory.xml to your kodi userdata folder
open your Windows Start menu and type
%APPDATA%\kodi\userdata

6 - try running the scripts on the command line

try saving the url of video, press y on the keyboard while and video is playing and select save url
that will create a text file on your desktop called video-url.txt

open a terminal and change directory to the desktop 

cd Desktop

Then try running rip-play script with video-url.txt file as an argument to the script, you need to run the script prefixed with bash, note there is a dash between rip and play.
rip-play and not rip play with a space between the words

eg

bash rip-play video-url.txt

you can also try add the full path to the script as well

7 - windows system path bug

there is a bug where if you have a really long windows system file path windows seems to forget the location of applications you have installed

try opening your windows system path in system preferences but dont edit anything just click ok
sometimes that makes windows remember where you have installed things
Double check you havent made a typo and you are seperating the paths to applications with a semicolon except at the end of the system path

To debug this issue we need to check if you can run rip-play script on the command line with the video-url text file

if you can run the script with rip-play video-urlin the terminal then you have installed ffmpeg, cygwin and the scripts 
but if you have to specify the full path to the script then there is a problem with you windows system path

you cant run the scripts from within kodi, but they work on the command line
the problem could be your windows system path or the location of the files

**Comment by sumitdipsite2005** [comment]
1 - Check
2 - Check
3 - Check
4 - Check
5 - Check
6 - Doesn't work. Error in cmd - bash: rip-play: No such file or directory
Though rip-play path is added in the environment variable, it is not recognized.
One thing that i notice is the rip-play file type is "file" and not "application" as for say ffmpeg, which is recognizable from the cmd. Could it be an issue? Do you have command to make the files in the git cloned repo executables?
7. Check.

I hope this helps.

**Comment by sumitdipsite2005** [comment]
Okay on further troubleshooting - i updated the windows path without using the hmepath variable. And added the extension exe to rip-play.

Now i get the below error:
C:\Users\Me>bash rip-play videourl.txt
videourl.txt: No such file or directoryvq=    0KB sq=    0B f=0/0

Note: the url that is getting saved to the desktop does not a hyphen between "video" and "url" in my case. But there is indeed a file by the name "videourl.txt" at the desktop, but the rip-play not able to recognize it now.

What other location it is searching for? And do i need to change file extension of all the files in the repo to exe?

Update - if i try C:\Users\Me>bash rip-play "stream url" then it works. It is just that it is not able to read off the txt file on the desktop.

**Comment by sumitdipsite2005** [comment]
C:\Users\Sumit\Desktop>bash rip-play videourl.txt
: Invalid argument.hopto.org:8080"  KB vq=    0KB sq=    0B f=0/0

C:\Users\Sumit\Desktop>bash rip-play videourl.txt
"rtmp://95.211.205.201/live playpath=setar1aa?id=11439&pk=db1d613403ced41776685317ad8653a8f1465c2028a80aeb6edc729e06868316 pageURL=http://www.p3g.tv/embedplayer/setar1aa/2/620/490 swfUrl=http://www.p3g.tv/resources/scripts/eplayer.swf conn=: No such file or directoryve=true"

What i understand is that is the code not mature enough currently to handle complex urls?Need your help in evolving this because i see lot of potential in this.
Thanks and merry Christmas and happy holidays!

**Comment by sumitdipsite2005** [comment]
Just to add one final word about the issue that i face on this on mac -
The command rip-play works perfectly fine when run from the terminal e.g. -
$HOME/git/kodi-playercorefactory/bash-scripts-macosx/rip-play video-url-12-25-15-15-18.txt

But when run from the Kodi - nothing happens. No video starts. No message in Kodi. The video just stops in Kodi. Thats it. Is there any debug log created? What am i missing both on windows and on mac? This is splitting my hair apart!

**Comment by NapoleonWils0n** [comment]
HI Mate

Sorry your having a bit of grief getting set up.
The file is called videourl.txt on windows, my bad mate
So the command doesnt work from the command line when you run: bash rip-play videourl.txt

Have you tried specifying the full path to the script: bash C:\UserName\git\kodi-playercorefactory\bash-scripts-windows\rip-play videourl.txt

You shouldnt add the .exe extension to the scripts, because they are bash scripts, they dont have a file extension, so you need to remove the .exe extensions you have added. The scripts are already executable. The file type should be file and not application

The git repository needs to be in a folder called git in your home folder, so the path should look like this: C:\UserName\git\kodi-playercorefactory\

The bash scripts should catch 99% of video urls, if a video url isnt working i can just update the code to catch the video url and then it should work

Have you tried several different links from different addons or are you just having problem with one link

Do you have sed. grep and cat installed with cygwin on windows
what happens if you type:
bash cat
bash sed
bash grep

Mac OSX El Capitan has broken a lot of programs and has stopped the scripts working from within Kodi, but the scripts still work on the command line. Have to wait for Apple to fix all the El Capitan bugs for the scripts to work again from within Kodi

I know the bash scripts work from within Kodi on Mavericks to Yosemite, it just the El Capitan that has broken the scripts from within Kodi

What version of Mac osx and Windows are you using ? 

If you are using Mac OSX El Capitan you need to create a folder called bin and install ffmpeg, ffplay and ffprobe into the bin folder, see the git repo wiki which has the El Capitan ffmpeg fix

In Kodi you can turn on the debug log
Go to System Settings, then click the debugging tab, then select Enable debug logging

The log file is created in kodi/temp/kodi.log one level up from the kodi userdata 

Location of the userdata folder

Operative system File path
Android Android/data/org.xbmc.kodi/files/.kodi/userdata/ (see note)
iOS /private/var/mobile/Library/Preferences/Kodi/userdata/
Linux ~/.kodi/userdata/
Mac /Users//Library/Application Support/Kodi/userdata/ (see note)
OpenELEC /storage/.kodi/userdata/
Windows Start - type %APPDATA%\kodi\userdata - press

Debugging problems can be frustrating, i spend a lot of time trying to figure out issues

If it helps you can try think of debuging in mechanical terms, eg  a problem with a car, you turn the key and press the accelarator but nothing happens, at what point is it failing, what are all the possible reasons for it failing, faulty pedal, no petrol etc. 

The best way to debug the problem is to start from scratch and redo the install on windows and mac osx step by step, i know thats a pain but there must be something your missing, i dont mean that in a bad way. I have spent many hours fixing bugs and the problem was just a typo. 

If you get fed up with mac osx and windows the set up on Ubuntu literally takes 5 minutes

**Comment by sumitdipsite2005** [comment]
Thanks for the reply mate.

When i type these:
bash cat
bash sed
bash grep

the result is:
C:\Users\Username>bash cat
/usr/bin/cat: /usr/bin/cat: cannot execute binary file

And when i run pointing to the location of cat, sed and grep:
C:\Users\Username>bash C:\cygwin64\bin\cat
C:\cygwin64\bin\cat: C:\cygwin64\bin\cat: cannot execute binary file

I can surely see the cat, sed and grep exes in the location - C:\cygwin64\bin\cat - so pretty sure they got installed.

Not sure this is the expected output.
I have already installed this 5-6 time now, so not sure reinstalling is an option now.
Done fresh install on two separate windows but still wouldn't work. Done it on a mac (El Capitan) still wouldn't work.

Maybe you can try a fresh install on windows 10 or El Capitan and it might turn out to be a known issue of this not working on them!

**Comment by sumitdipsite2005** [comment]
Tell you what - try with this URL - http://motorsport.hopto.org:8081 - yourself and let me kow the result if it is a url issue.
I have infact tried this with several different addons - but unfortunately it doesn't work with any.

I cannot even find cygwin under my installed programs - i am sorry but i am starting to feel creepy about these little programs!

**Comment by NapoleonWils0n** [comment]
I tried that url and it works fine i can play and record it no problem

I have tested the scripts on Windows 10, Mac osx El Capitan, OSX Mavericks, Arch linux, Ubuntu and Openbsd

Works fine on Windows 10 but as i said Mac osx El Capitan has broken a lot of programs and has stopped the script running from within Kodi, but the scripts still work on the command line

Either you have a problem with both windows and mac osx that is stopping the scripts working, 
some security setting or you are missing something during the install

**Comment by sumitdipsite2005** [comment]
How can i troubleshoot this?

**Comment by NapoleonWils0n** [comment]
Hi Mate 

You can have a look at the console app on macosx in Application/utilities
There is probably something simmilar on windows
You can also enable the kodi log in system settings

there are only 4 things really needed to get the scripts working

1 - downloading the kodi-playercorefactory git repo into a folder called git in your home 
2 - installing ffmpeg, ffplay and ffprobe
3 - adding the scripts location to your ~/.bashrc on mac, or windows system path on windows
4 - copying the playercorefactory.xml to your kodi userdata directory

on windows you do need to install cygwin and some additional tools and add them to your windows system path

So the things to check are the location of the git repository is yourhome/git/kodi-playercorefactory
That ffmpeg is installed, you can test by typing bash ffmpeg in the terminal on windows, or ffmpeg in a terminal on macosx
You have add the path to the scripts to your ~/.bashrc to windows system path
You can run the scripts from the command line
And you have copied the correct playercorefactory.xml file for your operating system to your kodi userdata directory

I dont know if you have any security settings that only allow you to run programs from the mac osx store or windows store
Firewall settings wont stop the scripts from working
The scripts are already executable so that isnt a issue
You could check the file permissions of the git folder and ffmpeg, ffplay and ffprobe
