### ISSUE TITLE
Recording from MLB.tv 

### ISSUE THREAD

**Issue by Ibrahim2311** [NapoleonWils0n/kodi-playercorefactory#32]
Hi Mr. Napoleon ,
it's very nice work what you have developed here ,

but I have an issue , when recording from (MLB.tv) which is added from this repository (https://github.com/eracknaphobia/repo.eracknaphobia)

and to open these games (it requires user-name and password) I fill them as required ,
So I can watch MLB through Kodi , the problem is when trying to record these it shows flash error in the cmd then close (I had to screen record to capture it).

another thing is that only the full games can't be recorder , opened with vlc or mvp ..etc 
it catches the save url but it's shows an error when I open it in the internet browser as well .

So I'm going to attach the error message from cmd , the internet browser and the save url file .

hope you can help me with this please .
![error](https://cloud.githubusercontent.com/assets/21281149/18028978/a34654de-6c93-11e6-8e7e-f27d426aadf2.png)
[videourl-20-20-51.02.txt](https://github.com/NapoleonWils0n/kodi-playercorefactory/files/440770/videourl-20-20-51.02.txt)

**Comment by NapoleonWils0n** [comment]
Hi Mate

yes i can help

the url its a link to an m3u8 playlist with a user agent and cookie for authentication

If you have a look at videos 106 and 99 youll see i helped other users with recording live games from kodi paid addons

I know what the issue is with video streams that use cookies for authentican and how to extract the cookie and use it with ffmpeg to record or pass the cookie onto video players

However the only way i can do that is by playing the video, 
which would require login details so i can access the video to do some testing

When i helped out for users for video 99 and 106 they private messaged me on the kodi forum the user name and pass 
so i could login to the addon to test the video streams

obviously i wont share the details with anyone or make them public
if your not comfortable sharing your login details no problem 

Do you want to register on the kodi forum 
and then you can private message a user name and pass so i can install the addon and login to mlb. tv to do some testing

let me know which section in the addon you want to record from

http://forum.kodi.tv/showthread.php?tid=216111

**Comment by Ibrahim2311** [comment]
Yes Mr. Napoleon , 
Thanks for fast response ,
and I'll share it with you(user and password) .
I'm signing up right now .

**Comment by Ibrahim2311** [comment]
I've signed up with hema2311 username , but the site doesn't allow me to send messages yet I think .

Can I send you them through email ? (I'll appreciate that) .

**Comment by NapoleonWils0n** [comment]
hi mate

you should see a button named pm under posts by me on the forum

just click the pm and you should be able to send me a message

**Comment by Ibrahim2311** [comment]
It seems it doesn't available for me (it's not appearing) , 

you can send me a message then I could reply to you may be that would work , this is my username (hema2311) .

or we can have the chat on skype : Ibrahim Hadidi

**Comment by NapoleonWils0n** [comment]
hi mate

you may need to post on the forum first
then ill be able to pm you

if i search for you username doesnt show up yet

**Comment by Ibrahim2311** [comment]
I can't do that as well . But let me check something
![capture](https://cloud.githubusercontent.com/assets/21281149/18034535/2ab90006-6d48-11e6-984b-3c39be190241.PNG)

**Comment by NapoleonWils0n** [comment]
Hi Mate
Your account might be awaiting activation

**Comment by Ibrahim2311** [comment]
Hi Mr Napoleon .
Thanks for your cooperation and patience .
But can't we have another way to send you the info (user and password)
Since I'm on a project and that would be a life saver , I'll appreciate if we can do that in another way .

**Comment by NapoleonWils0n** [comment]
hi mate

your account on the kodi forum may not have been activated yet because its a sunday and the moderators havent got round to it

anyway it takes several days to create the new code to record the video stream, and do all the testing on 3 operating systems
add the new code to github, record a new video and upload it to youtube

so even if you gave me the username ans pass today it will still be several days to a week before its ready 

you cant private message on github, so need to use kodi forum instead
you could try posting a message on the forum tommorw

**Comment by Ibrahim2311** [comment]
Thanks a lot , I appreciate your cooperation , and wish that you do it soon (less than 4 days) it would be a life saver for me , 
again thank you Mr Napoleon , I hope they finalize my activation process tomorrow , so that I can send you the message .

**Comment by Ibrahim2311** [comment]
Hi Mr Napoleon , 
I think it would be too late once they fully activate my account .
I really appreciate if you can provide me with any social or private way of contact ,
then I can make a post on forum so that it would be official issue .

I really really appreciate doing that . 
here is my email : i.s.h.94@hotmail.com

If you can't help me with this Please just tell me , so that I consider it .
