### ISSUE TITLE
playercorefactory error on line 69

### ISSUE THREAD

**Issue by bigo229** [NapoleonWils0n/kodi-playercorefactory#38]
Running on Windows 8.1, install & setup folders as per your readme for windows
after pressing y in kodi save url works ok, kodi play on vlc ok, kod play on mpv not working or the record function.

checked all folders & reset path but no go

can record ok using your old scripts, i opened up cmd (Terminal) in windows & ran the following command,
bash rip-record videourl=14-57-01.24.txt

bash rip-record videourl=14-57-01.24.txt/cygdrive/c:/users/++++++/git/kodi-playercorefactory/bash-scripts-windows/rip-record:  rip-record  line 69: syntax error near unexpected token '>'
bash rip-record videourl=14-57-01.24.txt/cygdrive/c:/users/++++++/git/kodi-playercorefactory/bash-scripts-windows/rip-record:  rip-record  line 69: ' $HTTP>'

Any Ideas, i have installed playercorefactory on kodi running ubuntu 16.04 64-bit and works perfectly
ok

Now pulling my hair out.

Bigo

**Comment by NapoleonWils0n** [comment]
Hi Bigo

I have fixed the error in the windows rip-record script on line 69 ( typo )
Do a git pull to update

I have had other users get everything working on Windows 8.1 
So i know the scripts do work

Im not a Windows user,
and have only used Windows about 15 - 20 times in my life

So apart from checking the steps in the read me and video and trying the windows system path fix i dont know what else to suggest

Windows is a pain to set up compared to Linux because you have to install everything manually and then add the install location to your system path

At least you managed to get everything working on Ubuntu

I also have a thread on the kodi forum, 
you could submit a post and see if any other Windows users can help out

http://forum.kodi.tv/showthread.php?tid=216111

Other wise can only suggest keep plugging away 
( or just switch the machine to linux and get everything working in 5 minutes )

:)

**Comment by bigo229** [comment]
Many thanks for your very quick reply , i will try everything you suggested and let you know if i have any more problems

Bigo

**Comment by bigo229** [comment]
Hi, Issue now sorted many thanks , had to reset the path a few times & reboot Kodi a few times but now all working ok.

Many Thanks for your very quick response & quick repair to the windows rip-record script

Bigo

**Comment by NapoleonWils0n** [comment]
hi bigo 

glad you got it working
at least you know how to fix it the issue if it happens again
