### ISSUE TITLE
virtual box

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#39]
This is probably a stupid question, but which way  is easier installing linux to windows or windows to linux in virtual box. Do you have a video on it?

**Comment by NapoleonWils0n** [comment]
Hi Steve

Not a stupid question, quite the reverse
So you want to know about running linux or windows in a virtual machine

## You dont want to use virtualbox for a couple of reasons
- Sometimes you update your kernel on Linux and then virtualbox stops working because virtualbox needs to be updated to work with the new kernel, so you have to wait for an update before it works again
- you have to install extension packs in the guest operating system and these have to match the version of virtualbox you are using and you keep having to update them

## you want libvirt, qemu, kvm and virt-manager

Virt-manager is a really nice gui program that you can use to create and manage virtual machines

You can create a virtual machine of practically anything

### Hardware support

KVM requires that the virtual machine host's processor has virtualization support (named VT-x for Intel processors and AMD-V for AMD processors). You can check whether your processor supports hardware virtualization with the following command:
- run the following command in the linux terminal to see if you have hardware support

```
lscpu
```

Your processor supports virtualization only if there is a line telling you so.

### lots of ram

Windows 10 needs a minimum of 2 gig of ram, my laptop only has 4gig of ram but it can run Windows 10 as a virtual machine

I would recommend at least 8 gig of ram, more if possible

### 64bit and 32bit

If you machine is 32bit you cant create 64bit virtual machine
So its better if you have a 64 bit machine

### videos showing virt-manager in action with windows and linux

I dont have any videos about installing libvirtd, qemu, kvm and virt-manager

But if you look at all the Windows, Debian, Ubuntu and Linux Mint videos they are all running as virtual machines using virt-manager
- [windows](https://www.youtube.com/watch?v=syiIx8y__PY)
- [ubuntu](https://www.youtube.com/watch?v=3pC8kMbAhKw)
- [Debian](https://www.youtube.com/watch?v=m3tLSDK0cXY)
- [Linux Mint](https://www.youtube.com/watch?v=zhwvMMdLaFw)

### usb passthru

libvirtd supports usb passthru which means you can map internal and external devices directly to the virtual machine

for instance run Kali linux as a virtual machine and plug in a usb wifi adaptor and map it directly to the virtual machine so you can use the wifi adapter for wifi hacking

or if you have a second graphics card you can map it to a virtual windows machine and get about near native graphics performance

If you search for Windows qemu on Youtube you will get some videos about running Windows as a virtual machine using qemu on linux
- [Windows qemu on Youtube](https://www.youtube.com/results?search_query=windows+qemu)

### Windows 10 work really well with libvirtd

Windows 10 works really well running as virtual machine using libvirtd and virt-manager

### Windows 10 install

When you run the Windows install dont use the express wizard thing,
you need to choose custom install and then just click next and accept all the defaults

I had to use the custom install to select the virtual drive to install windows onto

### Linux distros that dont work well with libvirtd
- Linux Mint ( Cinnamon desktop )
- Ubuntu ( unity )

Some desktops that use lots of overlays and visual effects like Cinnamon and Unity dont work well in a virtual machine.

Gnome 3 works ok, and Mate works as well

### links for  libvirt, qemu, kvm and virt-manager
- [virt-manager](https://virt-manager.org/)
- [my note on arch linux virt-manager install](https://github.com/NapoleonWils0n/cerberus/blob/master/arch-linux/qemu-libvirt.sh)
- [libvirt](https://wiki.archlinux.org/index.php/Libvirt)
- [qemu](https://wiki.archlinux.org/index.php/QEMU)
- [kvm](https://wiki.archlinux.org/index.php/KVM)
