### ISSUE TITLE
adobe flash player for arch linux

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#40]

**Comment by steve55792** [comment]
Is there away to get adobe flash player in arch linux. im using iceweasel, far as i got is extracting it to the desktop. Another question is there a way to record from Screambox website?

**Comment by NapoleonWils0n** [comment]
hi steve

if you google for "arch flash player" the first link is for the arch wiki browser plugins

that tells you how to install flash

not sure about screambox as its a paid site cant see any kodi addons for it
and tools like youtube-dl or rtmpdump probably wouldnt work unless you where logged in

**Comment by steve55792** [comment]
nope no kodi addon yet, i asked them if there ever gonna be one  and they said wouldlook into it and how would a person use youtube-dl or rtmpdump on a browser?

**Comment by NapoleonWils0n** [comment]
hi steve

youtube-dl has a list if sites it can dowload from
i doubt screambox would be supported since its a pay site

heres how to use rtmpsrv which comes with rtmpdump
but you would need to be logged in anyway so wouldnt do you any good

https://github.com/NapoleonWils0n/cerberus/blob/master/rtmpdump/rtmpdump.sh

the issue tracker is for issue with the scripts
can you use the kodi forum instead for questions otherwise it makes it look like there is an unresolved issue withe scripts
