### ISSUE TITLE
Installing Kodi

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#48]
Sorry to bother you about it but what is the correct procedure to install kodi 16 Jarvis on Ubuntu Mate, somehow i accidently lost kodi. I tried every way to put it back on, but i got no where.

                                                                                            Thank You
                                                                                               Steve

**Comment by NapoleonWils0n** [comment]
hi steve

no problem mate

open the terminal and run the following command

```
sudo apt install kodi
```

it should prompt you for your admin password
i recently tested all the scripts on the latest version of ubuntu mate and everything is working

let me know if that resolves the issue

**Comment by steve55792** [comment]
I got this error after i ran the command  :Unpacking kodi (2:18.0~git20161207.0200-5e57a75-0yakkety) ...
dpkg: error processing archive /var/cache/apt/archives/kodi_2%3a18.0~git20161207.0200-5e57a75-0yakkety_all.deb (--unpack):
 trying to overwrite '/usr/share/icons/hicolor/128x128/apps/kodi.png', which is also in package kodi-data 16.1+dfsg1-2
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/kodi_2%3a18.0~git20161207.0200-5e57a75-0yakkety_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by NapoleonWils0n** [comment]
Hi Mate

You could try running this command which should unistall any left over bits from Kodi

```
sudo apt-get purge kodi*
```

* and then try runnning this command to remove any unused packages

```
sudo apt-get autoremove
```

* then try reinstalling kodi with this command 

```
sudo apt install kodi
```

when i googled for "dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)"
those are the results i got 

let me know if that helps mate

**Comment by steve55792** [comment]
I got it back, thank you for helping me again, i really appreciate it. Now kodi is up to 18 Alpha. I'm not touching anything except for my addons.LOL.

**Comment by NapoleonWils0n** [comment]
Hi Mate

Glad you got Kodi back

The t3rmin8tor ( mentioned in the last video ) is just building a Linux GUI installer for all the programs and scripts,
as well as a Windows GUI installer as well

And a GUI app you can use instead of the command line to add a url or text file with url,
to record and a duration for the recording

**Comment by NapoleonWils0n** [comment]
Hi Mate

Ill close your issues
Im setting up a new site for tech support as the thread on the kodi forum got closed

**Comment by steve55792** [comment]
What you are saying that we can use an app instead of typing the text of an url text file, like if i wanna record hbo channel i dont have to type the whole line out? yeah thats a bummer about kodi forum closing. I wonder why?

**Comment by NapoleonWils0n** [comment]
Hi Mate

You could still record from within Kodi as normal

And then you could save the url from Kodi,
but instead of using the command line to record you would have a GUI app to select the text file or enter a url, and then fill in the recording duration

Does the same thing as recording on the command line but with a GUI

The Kodi forum hasnt been closed, just my thread on the Kodi forum

The thread got closed because there were some posts that mentioned addons like Exodus that are banned on the forum ( mentioned by me, so only myself to blame )

But im setting up another site for tech support so not to worry, will have a new home soon
