### ISSUE TITLE
MLB.tv Problem

### ISSUE THREAD

**Issue by bush2000** [NapoleonWils0n/kodi-playercorefactory#53]
Hi. Napoleon

First of all..Your job is awesome :) 

I have done everything in your manual. However, there is an error in the MLB recording process. It seems that the address of the file is not recognized.

When you view your YouTube video, an mkv file is created when you press the Record button. However, in my case, the following error occurs and recording is not done.

Did MLB know how to record like this? :)

Would you review it?

Thanks in advance.

**Comment by NapoleonWils0n** [comment]
Hi Mate

Sorry its not working for you 

I dont know if they have changed the urls since i made the video
I have seen the unable to open keyfile error on some other streams before

could you run a few tests and see if we can resolve the issue

1) can you make sure you are running the latest version of the scripts by doing a git pull

* open the windows command prompt and change into the directory with the scripts by running the the following command

```
cd git/kodi-playercorefactory
```

* do a git pull by running the following command in the windows command prompt

```
git pull
```

2) Check which version of ffmpeg you are using by running the following command in the windows command prompt

```
ffmpeg
```

that should tell you which version of ffmpeg you are running
im running ffmpeg 3.2.2

3) does using mpv as an external player to play the link from kodi work

can you play the video and press Y on the keyboard while its playing and then select mpv in the menu and see if it can play the video 

If doing a git pull to update the scripts doesnt resolve the issue we can move onto some more debugging

cheers mate

**Comment by bush2000** [comment]
Thanks. Napoleon.

First, I checked that both # 1 and # 2 are up to date.

But the # 3 mpv player is not working properly.
Also, mpv player can not play other movie files. (Black screen issue)  I added the "mpv.conf" file to fix this problem, but it did not change.

When I read other users' posts, the black screen problem seems to exist in too many cases. :)

As for MLB.tv, when mpv is executed, there is no response after the following screen appears.

It is possible that I have installed some programs incorrectly. So I will try to review again in a few days.

I plan to do this on my MacBook over the weekend.

**Comment by NapoleonWils0n** [comment]
Hi Mate

thanks for testing everything

## mpv 

i have found mpv.conf with this resolved the black screen issue

```
vo=direct3d
```

* but maybe your version of windows needs a different fix, works for me on Windows 10

### mlb

I have updated the scripts recently

but i saved the url from mlb,
and made sure the new scripts regular expression still caught the url

it should match this regular expression

```
url matches:  $cookiem3u8uagent
```

## save url and email it

* could you save the url from mlb and email it to me here

t43invisibleman@gmail.com

so i can test if the regular expression catches the url

## mac install

you should find the mac install quicker than windows

**Comment by NapoleonWils0n** [comment]
hi mate 

ill close this issue as the scripts record the video

chat via email instaed
