### ISSUE TITLE
m3u8-link-checker

### ISSUE THREAD

**Issue by privatesam** [NapoleonWils0n/kodi-playercorefactory#62]
Big thank you for all these useful scripts and tutorial videos.

I have an issue with the m3u8-link-checker bash script in linux.  It checks *.m3u8 files fine but its incorrect with *.ts links which I know are fine in VLC.  Whats weird is if I change the extension to *.m3u8 on a working *.ts link the script correctly checks it.  I can't see anything in your code that suggests it can't recognise and therefore test a *.ts link - more I suspect its ffprobe trying the *.ts and giving up too quickly?

**Comment by NapoleonWils0n** [comment]
Hi Mate

the regular expression does match ts files 
just looks like ffprobe doesnt check ts files

i think you have hit the nail on the head

i suspect the issue is this

m3u8 playlists contain links to *.ts files
and you dont normally deliver streams as ts files but as an m3u8 playlist

its only that kodi uses dodgy streams that you get ts links

looks like ffprobe just checks for m3u8 playlists and not the actual ts files
i think thats just the way ffprobe works

the only work around is to create m3u8 files and add the ts links to those
and then add those m3u8 links to a another m3u8 file and check that

**Comment by NapoleonWils0n** [comment]
Hi Mate

maybe it would be better to use something like wget or curl to check for 404 errors with ts links

**Comment by privatesam** [comment]
Thanks for reply - and thanks for confirming this.  I think I'll just add some code to change the *.ts to *.m3u8 so ffprobe can do its work.

One more question!  Is there a quick way to modify the  m3u8-link-checker  script to overwrite the input file instead of creating a new file-checked.m3u8?  I've poked around in the script and added some -i flags to some sed randomly but with no luck.

**Comment by NapoleonWils0n** [comment]
hi mate

if you want to edit the code best to copy the script and rename it 
and put it in a bin folder in your home directory

otherwise if you do a git pull your changes may be overwritten

you could try making the following changes

on line 40 change 

-eq 0

to 

eq 1

that means if the ffprobe command failed

then youll need to change the sed command on line 40
the grep command before sed matches the link and the line above it with the channel name
then pipes it into sed

you would need to work how to get sed to delete the 2 lines piped in from grep on stdin
have to google for that one maybe have a look on stackoverflow

also remove line 44

**Comment by privatesam** [comment]
BTW if anyone is looking to overwrite the original file with the output from m3u8-link-checker just add this line to the 2nd to last line of your script:
`
mv $outfile $file
`
just before the 
 `exit "$SUCCESS" # exit`

**Comment by privatesam** [comment]
Sorry to reopen this but I have discovered something.  FFprobe does work on .ts files, in fact is works with pretty much every video file I can find - .mkv, .mp4 etc.  The problem the m3u8-link-checker actually has is with a small bit of code designed to avoid image files listed in an m3u for the logo.  If you remove this piece of code on line 38:

`| grep -v '.[(jpg|png|gif|svg)]$')`

the checker will now happily check all the video links (.ts, .mkv, .mp4 etc)  in your m3u playlist.  The problem is it now also checks any image URLs it comes across.  I'm going to play with the code and see I can't get this straightened out.

**Comment by NapoleonWils0n** [comment]
hi mate

good spot
thanks for helping out

as you know we cant just search for video extensions as some streams have no extension
so had to do a negative search for a list of ext to exclude

let me know if you have any bright ideas on how to resolve the issue

**Comment by NapoleonWils0n** [comment]
added new regex
