### ISSUE TITLE
renaming

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#68]
Hi NapoleonWilson,

How would you Rename the ripconfig file in Windows in the terminal for changing the directory for the videos? You probably had it in the last video but i must of missed it somehow.

                                                                                                       Thanks
                                                                                                         Steve

**Comment by NapoleonWils0n** [comment]
hi steve

here are the steps to set up ripconfig on windows 

## 1 - do a git pull to update

open the windows command prompt

* change into the git/kodi-playercorefactory directory

```
cd git/kodi-playercorefactory
```

* do a git pull to update

```
git pull
```

## ripconfig set up

copy the git/kodi-playercorefactory/ripconfig/ripconfig file 
into your home folder

so the location of the file should be home/ripconfig

### edit the ripconfig file

you must use notepad++ to edit the ripconfig file otherwise the line endings get messed up

right click on the ripconfig file in your home and select open with notepad++

* add your path between the double quotes for ripdir=""

```
ripdir=""
```

you must use forward slashes / in the file path
and not back slashes \

so to change the recording directory to the Videos folder in your home you would change the code to this

```
$USERPROFILE/Videos/
```

you can also add the full path to your C, D or other drive

* if you arent using ssh you you can remove the ripssh="" section

## rename the ripconfig file with the windows command prompt

open the windows command prompt
it will open to your home folder

* check you are in the correct directory by running the pwd command to show the current directory

```
pwd
```

* list the files to make sure the ripconfig file is in your home directory

```
ls
```

* rename the ripconfig file and add a dot prefix

```
mv ripcofig .ripconfig
```

note the dot before the second ripconfig

now when you record it will record to the new destination

if you add in the wrong file path to the ripconfig file
or the drive isnt mounted the scripts check if the directory exists and if it doesnt it will fall back to recoring on the desktop

that way the video will still record if the ripconfig file path is wrong

**Comment by NapoleonWils0n** [comment]
hi steve

the path in the .ripconfig file should look something like this

```
ripdir="$USERPOFILE/Videos/"
```

have a look at the readme page in the ripconfig directory for more info

**Comment by steve55792** [comment]
Thank You, does the $ gotta be there before userprofile name and gotta be capitalized?

**Comment by steve55792** [comment]
Thank You, does the $ gotta be there before userprofile name and gotta be capitalized?

**Comment by NapoleonWils0n** [comment]
hi mate
yes there must be a $ before userprofile 

and userprofile must be in all caps

```
$USERPROFILE
```

userprofile is a shortcut for your home folder on windows

**Comment by steve55792** [comment]
I got this so far:
ripdir="$STEVE/Videos/"
ripssh="$STEVE/Videos/"
and i renamed it  mv ripcofig .ripconfig into my home folder and it still records on the desktop.

**Comment by NapoleonWils0n** [comment]
hi mate

that wont work

replace your name with  $USERPROFILE

**Comment by steve55792** [comment]
and still save it as mv ripcofig .ripconfig?

**Comment by steve55792** [comment]
i figured it out and just changed the directory in the rip-record file and it did save it in the video folder

**Comment by NapoleonWils0n** [comment]
hi mate

dont edit the rip-record script
because any changes will be overwritten when you do a got pull

you need to use the ripconfig file

**Comment by steve55792** [comment]
Ok, i switch it back.  so save the ripconfig file as  mv ripcofig .ripconfig?

**Comment by NapoleonWils0n** [comment]
hi mate

replace your name with $USERPROFILE in the ripconfig file

then you need to use the windows command prompt to rename the ripconfig file with a dot prefix
by running following command

```
mv ripconfig .ripconfig
```

**Comment by steve55792** [comment]
i got it working now

**Comment by steve55792** [comment]
Thank you

**Comment by NapoleonWils0n** [comment]
hi steve
no problem mate
