### ISSUE TITLE
Is there a way to record from NHL.TV in Kodi?

### ISSUE THREAD

**Issue by rdwenrich** [NapoleonWils0n/kodi-playercorefactory#7]
This is my save url file:
[video-url-02-13-16-18-35.txt](https://github.com/NapoleonWils0n/kodi-playercorefactory/files/129549/video-url-02-13-16-18-35.txt)
I am trying to record this because my internet is not that good for live streaming. I have an NHL.TV account and I can play Ice Hockey games in Kodi with the NHL.TV addon. Thanks.

Dennis

**Comment by NapoleonWils0n** [comment]
Hi Dennis
The video stream uses cookies
So ill have to add some new code to the scripts to get ffmpeg to use the cookies from the video stream

i dont have NHL.TV account so i cant test the code
So ill post a comment here when i have added the code and you can do a git pull and test if it works or not

Also which operating system do you use, windows, macosx or linux

**Comment by rdwenrich** [comment]
Thank you for helping me to get this to work. I am using Debian Linux testing version.

On NapoleonWils0n notifications@github.com, Feb 17, 2016 4:55 AM wrote:
Hi Dennis
It should be possible to record that stream, but i need add some code to the scripts first
Also i dont have a NHL.TV account so ill need your help to test everything works

If you look at the url you'll see its a link to an m3u8 video stream with User-Agent http header and it also uses a cookie for authentication, just like a cookie in a browser

So the reason its not working at the moment is because of the cookie authentication
ffmpeg can save cookies files so it can record the video stream so it should work

heres what i need to do

1 - create a regular expression to match urls that contain the word cookie
2 - store the cookie in a variable called cookie
3 - create a new ffmpeg command  to use the cookie variable and save it in a text files, which fingers crossed should let you record the video

After i have created the command ill add it to the git repository
As i said i dont have a NHL.TV account so ill need your help to test it works

Ill leave a comment here and let you know when ive added the code and then you can do a git pull and test if it works or not

Also which operating system do you use, windows, macosx or linux

---

**Comment by NapoleonWils0n** [comment]
Hi Dennis
I have just added some new code to the scripts,
so ffmpeg can record video streams that use cookies like the nhl stream

Do a git pull to update

Can you test recording and playing and see if it works from within kodi and on the command line, cheers
I dont have an nhl account so i havent been able to test if the code works or not, in theory it should

only added the code the the bash scripts for linux at the moment

changed 3 files

$COOKIE is the new stuff

video-regex.sh
https://github.com/NapoleonWils0n/kodi-playercorefactory/blob/master/bash-scripts/video-regex.sh

rip-record
https://github.com/NapoleonWils0n/kodi-playercorefactory/blob/master/bash-scripts/rip-record

rip-play
https://github.com/NapoleonWils0n/kodi-playercorefactory/blob/master/bash-scripts/rip-play

**Comment by rdwenrich** [comment]
[Test_VLC_NHL.TV.pdf](https://github.com/NapoleonWils0n/kodi-playercorefactory/files/133714/Test_VLC_NHL.TV.pdf)
Hi Napoleon,

I tired opening a game and pressed y and vlc and here is the log I received. I hope it will help to understand the problem.

Thanks,
Dennis

Date: Tue, 16 Feb 2016 19:13:31 -0800

**Comment by NapoleonWils0n** [comment]
Hi Dennis 
the new code is using ffplay to play the video and ffmpeg to record
so trying to open the video wth vlc wont work

you need to press y on the keyboard while the video is playing and select "play" to open the video in ffplay, or record to record the stream with ffmpeg

**Comment by rdwenrich** [comment]
[rip-play_test.txt.pdf](https://github.com/NapoleonWils0n/kodi-playercorefactory/files/135439/rip-play_test.txt.pdf)
[rip-record_test.pdf](https://github.com/NapoleonWils0n/kodi-playercorefactory/files/135440/rip-record_test.pdf)
[video-url-02-18-16-08-02.txt](https://github.com/NapoleonWils0n/kodi-playercorefactory/files/135444/video-url-02-18-16-08-02.txt)
 Hi Napoleon
I tried play and record in kodi and it said on the screen the external player is open but there was no ffplay or ffmeg process started or listed in my process list. Then I tried to save url and do rip-play and rip-record. I attached the files of results above.

**Comment by NapoleonWils0n** [comment]
Hi Dennis
the video is an hls encrypted stream
the error "unable to open key file"  is because the video is encrypted using key files and ffmpeg isnt able to use the key file to decrypt the video and play it

we are passing the cookie with ffmpeg but then it uses a key file which is the problem

so at the moment ffmpeg doesnt seem able to record hls encrypted video streams, they may fix it in the future i dont know
it might be possible to use wget to pass the cookie and then pipe the output into vlc

i dont have an nhl account so i cant run any tests
you could use wireshark to capture the network traffic while you play the video and inspect the traffic when the key files are used

ill remove the code from the git repo as its not working but ill archive it in case ffmpeg can record hls encrypted streams in the future

can only suggest you google for "nhl hls encrypted streams",  "ffmpeg unable to open key file" 

its an ffmpeg issue which is beyond my control, there may be another way to record the stream but thats something you'll have to look into because i dont have an nhl account so cant run any tests

Sorry i cant be more help
Maybe with a bit of donkey work you'll be able to figure something out
good luck

**Comment by rdwenrich** [comment]
Hi Napoleon,

Thank you very much for your efforts. I really appreciate it. I'll keep trying to find a solution.

Take care,

Dennis

Date: Wed, 17 Feb 2016 18:22:00 -0800
