### ISSUE TITLE
Kodi Record

### ISSUE THREAD

**Issue by Sparkplugs** [NapoleonWils0n/kodi-playercorefactory#71]
Hi Napoleon,

Hope you're keeping well.

I have a new laptop and running Linux Mint 18 - Sarah along with the new recently updated Kodi v17.1.
I've set up all my addons and installed playercorefactory as per your instructions. I've carried out a recent git pull and placed the playercorefactory.xml file in the .kodi/userdata folder. 
The problem is when I record, I press y at the start of the show, the menu drops down, I press the record command and then 3 files appear on my desktop, one after the other at about 10 second intervals and they're exactly 503bytes each in size. This happens on all my addons.
Now, I would usually blame myself for doing something wrong but I've already installed your system on to a desktop sometime ago and it works like a charm. I've also updated the kodi from v16 to v17 with no problems at all. The only difference is, the os on my desktop is Linux Mint 17 and this one is 18.

Any ideas or suggestions. Please let me know if you need any further info.

Greatly appreciate your help and all the work you do.

Many Thanks
Sparkplugs

**Comment by NapoleonWils0n** [comment]
hi sparkplugs

i think it may be the version of ffmpeg or rtmpdump may be rather old

check which version of ffmpeg and rtmpdump you are running on your new set up compared to the old set up

should be able to fix by installing a more recent version of ffmpeg from a ppa

**Comment by Sparkplugs** [comment]
Hi Napoleon,

We're getting somewhere, updated ffmpeg and rtmpdump and record works perfectly, but only on one addon.
When I try it on any of the others Kodi immediately comes up with 'finished recording' and no file appears on the desktop.
I also removed and reinstalled the addons, to see if it made any difference.

**Comment by NapoleonWils0n** [comment]
Hi Sparkplugs

im running ffmepg 3.2.4 the scripts work fine

what version of ffmepg are you ruuning

if you just type ffmpeg in the terminal and press return it will give you the ffmpeg version

havent come across an issue where the scripts only work with 1 addon

some things to try

1 - try sourcing your bashrc or bash profile

```
source ~/.bashrc
```

2  - try saving the urls from the addons and recording on the command line

3 - try rebooting

4 - try moving the ~/.kodi to the desktop and reopen kodi to recreate the .kodi folder

you can move the ~/.kodi to the desktop while kodi is closed
then reopen kodi and it will be like a fresh install

you will then need to reinstall the addons and copy the playercorefactory.xml file into place

you can always restore the .kodi folder from the dektop as well

let me know if any of that helps

**Comment by Sparkplugs** [comment]
Hi Napoleon,
I'm running ffmpeg version 3.3 and carried out your advice but still with no change. 
The only error on the Kodi log is:-
**ERROR: Control 50 in window 10025 has been asked to focus, but it can't**
I've tried searching for a fix on the error but can't find any solutions anywhere but not even sure if its the error that's causing the problem.

I think I'll remove the lot and start again from scratch. Thanks for your help and please drop me a note if you think of anything else.

Many Thanks
Sparkplugs

**Comment by NapoleonWils0n** [comment]
hi sparkplugs

when i did the video demo for linux mint i had to use a ppa to install ffmpeg
i dont think mint had ffmpeg in the main repo at the time for some reason

it could be a linux mint issue with kodi, you could try updating the software on mint and see if that helps

i find debian with backports to install the latest kodi and ffmpeg works well
and is a good mix of stable operating system and with backports you can install newer software

you may want to stick with mint but i have sometimes had issues with mint and ffmepg

and have found debian with backports to work better than things like ubuntu
there is an opition in the debian installer to enable backports

debian uses the gnome desktop and ubuntu is going to switch to gnome as well in the next release
you could always spin up a debian live cd and see what you think

otherwise you may need to do s little googling for the linux mint kodi issue

if i come across anything re your issue ill leave a comment

**Comment by Sparkplugs** [comment]
Hi Napoleon,

I think you're absolutely right. I'm sure its a Mint issue. 
I'm up for a challenge, I'll give debian a go and will let you know how I get on.

Thank you for all your help, really appreciate it.

Sparkplugs

**Comment by NapoleonWils0n** [comment]
hi sparkplugs

i have found mint to be a bit flaky and installing ffmpeg and codecs a bit of a pain

re debian

when you run the debian installer there is a section that lets you enable backports

backports let you install newer version of ffmpeg and kodi than in the main repo
you can also enable backports after the install if you miss the page in the installer 

i run debian myself on my macbook air
i just switched my second macbook air to freebsd which is why you will see the freebsd version of the scripts in the repo

on the mac i hold down alt when booting up the debian cd
then you see 2 disc icons appear 

1 - windows
2 - efi

you want to select the efi icon to install debian in efi

efi mode boots in a couple of seconds
if you dont install debian in efi mode it may take 30 seconds to boot up from legacy bios mode

may be different on windows machines

let me know if you need any help as i run debian myself and can give you a few pointers

**Comment by Sparkplugs** [comment]
Hi napoleon,
I'm confused already, which doesn't take much theses days.
I've found the debian download, it's amd64 version 8.7.1, but there are 3 dvd iso downloads. Is it really that big or do I just need the 1st iso disk to install it?

**Comment by NapoleonWils0n** [comment]
hi sparkplugs

we were all noobs once
didnt mean to baffle you mate

what i do is download the 64-bit pc netinst iso torrent from here

https://debian.org/distrib

and then burn it to a disc 

the netinst iso may not have all the wifi drivers
so its best to plug in ethernet when you are installing

if your computer doesnt have an ethernet port i would use a usb to ethernet adaptor

you get a prompt with the netinst install asking if you want to install a wifi driver from a usb drive during the install

you can google for which driver you need and copy it to a usb drive formatted to fat before hand and plug it in when prompted and it will install the wifi driver

but you can skip that and install the wifi driver after the install instead

so the steps would be

1 download the 64 bit pc netinst iso torrent

2 burn the iso to a disc

3 plug in ethernet

4 boot up the cd and you should see 2 options windows and efi, select efi

5 select the graphical install option and select the options for your lnaguage location etc

here is the debian admin install guide with screenshots for all the steps in the installer

https://debian-handbook.info/browse/stable/sect.installation-steps.html

when you get to the section of partition disc in the installer you want to select

Guided - use entire disk and set up encrypted lvm

and in the next section choose

All files in one partition (recommended for new users)

you can also choose which desktop enviormnet to install
the default is to install the gnome desktop but you can choose another desktop if you like

and also select backports during the install
which will let you install newer version of ffmpeg and kodi

 i have lots of debian tips and tricks ill be happy to show you once you up and running
like running your own dns server so your isp or google dont have a record of your dns request

you may find debian a little more technical than mint at first but stick with it as youll learn alot more

most linux distros are based on debian so one you get your head around debian you will be be able to use any debian based linux distro much more easily

if you get stuck on anything have a look at the debian handbook and if doesnt make sense give me a shout and ill point you in the right direction

**Comment by Sparkplugs** [comment]
That's perfect, thank you very much for the instructions, that's exactly what I need.
It's a shame, was going to visit the mother in law tomorrow but I really need to crack on with this.

Have a great day tomorrow and thanks again. I'll be in touch soon.
Sparkplugs

**Comment by NapoleonWils0n** [comment]
hi sparkplus

hope the screenshots help
a pictures is worth a thousand words sometimes

bob monkhouse (british comedian) on mother in laws 

My wife said: "Can my mother come down for the weekend?" 
So i said: "Why ?"
And she said: "Well, she's been up on the roof for two weeks already"
