### ISSUE TITLE
Saved Recording Directory

### ISSUE THREAD

**Issue by chrisgatesuk** [NapoleonWils0n/kodi-playercorefactory#97]
Is there a way to change the default recordings directory from the Desktop to somewhere else please?

**Comment by NapoleonWils0n** [comment]
hi mate

yes you can change the record destination folder

read me page about changing recording folder
https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/ripconfig

youtube video on changing recording destination
https://www.youtube.com/watch?v=-AwmB5XHstM

there is a new version of the script written in python called pilfer

so worked has switched to pilfer and i wont be making any updates to the kodi playercore factory bash scripts
they still work fine but wont be getting any updates

pilfer the new python script catches more urls and can do things the bash version cant
like decode url encoded strings

pilfer doesnt have a config file that lets you change the recording destination though
but you could always fork the git repo and edit the script and change the recording folder

https://github.com/NapoleonWils0n/pilfer

pilfer youtube videos
https://www.youtube.com/watch?v=uKRU74Uqj1s&list=PL7hhhG5qUoXmtylBpTV4AdjFkYOj2soEB

**Comment by Sparkplugs** [comment]
Hi Napoleon,
Do you recommend that we switch over to the Pilfer then? 
Is it possible to use Pilfer and Playercorefactory bash scripts side by side? Only I'm using Playercorefactory at the moment and it works like a dream but as you've mention there are some urls that won't record.

Many Thanks
Sparkplugs

**Comment by chrisgatesuk** [comment]
Thanks so much for this. If I upgrade to Pilfer, do I need to uninstall all the previous installations of Git, VLC, RipRecord, Seguin and FFMPEG? Or will Pilfer overwrite everything correctly?

Sent from my iPhone

On 27 Mar 2018, at 14:12, NapoleonWils0n <notifications@github.com<mailto:notifications@github.com>> wrote:


hi mate

yes you can change the record destination folder

read me page about changing recording folder
https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/ripconfig

youtube video on changing recording destination
https://www.youtube.com/watch?v=-AwmB5XHstM

there is a new version of the script written in python called pilfer

so worked has switched to pilfer and i wont be making any updates to the kodi playercore factory bash scripts
they still work fine but wont be getting any updates

pilfer the new python script catches more urls and can do things the bash version cant
like decode url encoded strings

pilfer doesnt have a config file that lets you change the recording destination though
but you could always fork the git repo and edit the script and change the recording folder

https://github.com/NapoleonWils0n/pilfer

pilfer youtube videos
https://www.youtube.com/watch?v=uKRU74Uqj1s&list=PL7hhhG5qUoXmtylBpTV4AdjFkYOj2soEB

**Comment by NapoleonWils0n** [comment]
Hi chaps

i would reccomend switching to pilfer as its more advanced 
and will catch pretty much all the urls from kodi except links that use a local proxy

links that use a local proxy dont have the actual link in the url you save from kodi all the time 
and sometimes append a token to the end of the url as well, that why those links dont work

it also seems to download videos alot faster than the bash version
also dev work has switched to pilfer and rip-record wont be getting any updates

if you are running windows you need to completly uninstall rip-record before installing pilfer
as they they use custom installers and wont work together

i think you may need to install the first version of pilfer and the install each update until you get to version 2 of pilfer

best thing to do is raise an issue on the pilfer windows installer page and explain you have rip-record installed
and want to unistall rip-record and then install pilfer and the t3rmin8tor who built the pilfer windows installer will talk you thru the steps needed to upgrade to pilfer

pilfer windows installer page
https://github.com/t3rmin8tor/pilfer-installer

if you are running linux, mac or freebsd you can have both pilfer and rip-record installed at the same time if you want

**Comment by NapoleonWils0n** [comment]
Hi chaps

pilfer can also rip the audio out of videos as well
which rip-record cant do

**Comment by Topicform** [comment]
Hi Jack :)

Il mar 27 mar 2018, 20:42 NapoleonWils0n <notifications@github.com> ha
scritto:

**Comment by Sparkplugs** [comment]
Hi Napoleon,

This might be a stupid question but I'm running Linux Debian and want to install Pilfer along side the bash version. What will happen when I press Y to record the url? 
Which one will open or is there a way of setting Y for bash and maybe Z for Pilfer? Or does the command list grow longer with the Pilfer actions.

Thanks for your help 
Sparkplugs

**Comment by NapoleonWils0n** [comment]
hi mate

not a stupid question at all

when you install pilfer you also download a new version of the playercorefactory.xml
and install it in tour kodi userdata folder

so you need to move the current playercorefcatory.xml file 
which is the version for rip-record out of the kodi userdata folder before installing the new pcf.xml for pilfer

the pilfer pcf.xml has settings to  record with a duration,  record just the audio with a duration
play the video with mpv and save the url

the y button is a keyboard shortcut in kodi and you cant have 2 pcf.xml files in your kodi userdata folder
and then press different keyboard shortcuts to launch each one

so what you need to do is just edit the new pilfer pcf.xml file and add any entrys you want fro the rip-record pcf.xml file

you can edit the pilfer pcf.xml file and add menu entrys from the rip-record pcf.xml file if you want

just make sure the menu names are different

eg

if you want to add the record menu entrys from rip-record pcf.xml file
to the pilfer pcf.xml file add a prefix to the menu entrys name

so instead of calling the menu entry record you would call it something like bash record

only thing to remember is the more entrys you have in the menu 
the more you have to scroll thru it in kodi

hope that all makes sense 
let me know if you get stuck

**Comment by Sparkplugs** [comment]
That makes perfect sense and works a treat.
Thank you very much Napoleon, very much appreciated.

**Comment by NapoleonWils0n** [comment]
hi mate

no problem
